[package]
name = "logging-lib"
version = "0.1.0"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono =  { version = "0.4.13", features = ["serde"] }
log = "0.4.11"
serde = "1.0.114"
serde_json = "1.0.57"
simplelog = "0.8.0"